packages:
  - ./apps/*
  - ./packages/*
  - ./packages/modules/*

catalog:
  # Build tools
  typescript: 5.6.2
  eslint: 9.31.0
  prettier: 3.6.2
  vite: 5.4.14
  tsup: 8.0.2
  rimraf: 3.0.2
  
  # React ecosystem
  react: 18.2.0
  react-dom: 18.2.0
  "@types/react": 18.3.2
  "@types/react-dom": 18.2.25
  "@types/node": 20.11.15
  
  # Medusa ecosystem
  "@medusajs/framework": 2.10.3
  "@medusajs/medusa": 2.10.3
  "@medusajs/admin-sdk": 2.10.3
  "@medusajs/cli": 2.10.3
  "@medusajs/dashboard": 2.10.3
  "@medusajs/test-utils": 2.10.3
  "@medusajs/medusa-oas-cli": 2.10.3
  "@medusajs/ui": 4.0.23
  "@medusajs/icons": 2.10.3
  "@medusajs/admin-bundler": 2.10.3
  "@medusajs/admin-shared": 2.10.3
  "@medusajs/admin-vite-plugin": 2.10.3
  "@medusajs/types": 2.10.3
  "@medusajs/ui-preset": 2.10.3
  "@medusajs/js-sdk": 2.10.3
  "@medusajs/workflows-sdk": 2.10.3
  "@medusajs/utils": 2.10.3
  "@medusajs/core-flows": 2.10.3
  "@medusajs/draft-order": 2.10.3
  
  # MikroORM
  "@mikro-orm/core": 6.4.3
  "@mikro-orm/cli": 6.4.3
  "@mikro-orm/knex": 6.4.3
  "@mikro-orm/migrations": 6.4.3
  "@mikro-orm/postgresql": 6.4.3
  
  # Database and utilities
  pg: 8.13.0
  awilix: 8.0.1
  lodash: 4.17.21
  zod: 3.25.76
  "posthog-node": 4.17.1
  "@babel/runtime": 7.24.0
  picomatch: 3.0.1
  "react-router-dom": 6.20.1
  express: 4.21.2
  stripe: 17.4.0
  "@types/express": 5.0.0
  jsonwebtoken: 9.0.2
  "@types/jsonwebtoken": 9.0.7
  algoliasearch: 5.40.0
  "date-fns": 2.30.0
  
  # Build and dev tools
  "@swc/core": 1.5.7
  "@swc/jest": 0.2.36
  jest: 29.7.0
  "ts-node": 10.9.2
  
  # Next.js for storefront
  next: 15.1.4
  
  # React ecosystem for admin
  "@tanstack/react-query": 5.64.2
  "@tanstack/react-table": 8.20.5
  "react-hook-form": 7.49.1
  
  # UI libraries
  "@radix-ui/react-dialog": 1.1.4
  "@hookform/resolvers": 3.4.2
  
  # Additional peer dependencies
  "@floating-ui/react-dom": 2.1.6
  "@ariakit/react": 0.4.19
  "@ariakit/react-core": 0.4.19
  "use-sync-external-store": 1.6.0
  "react-remove-scroll": 2.7.1
  "react-remove-scroll-bar": 2.3.8
  "react-style-singleton": 2.2.3
  "use-callback-ref": 1.3.3
  "use-sidecar": 1.1.3
  "radix-ui": 1.1.2
  
  # Workspace packages
  "@mercurjs/framework": workspace:*